spring:
  application:
    name: WeChatSummary

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  data:
    redis:
      host: localhost
      port: 46379

  rabbitmq:
    host: localhost
    port: 45672
    username: myuser
    password: secret

  datasource:
    url: jdbc:postgresql://localhost:45432/wechat
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  ai:
    openai:
      api-key: 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
      base-url: https://integrate.api.nvidia.com
      chat:
        options:
          model: deepseek-ai/deepseek-v4-pro
      audio:
        transcription:
          timeout: 60m
          base-url: http://localhost:48000/v1/
          options:
            model: large-v3

custom-ai:
  multimodal:
    base-url: https://integrate.api.nvidia.com/v1
    api-key: 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
    model: moonshotai/kimi-k2.6

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

storage:
  upload-dir: ${HOME}/uploads
