spring:
  application:
    name: WeChatSummary

  servlet:
    multipart:
      max-file-size: 20GB
      max-request-size: 20GB

  data:
    redis:
      host: localhost
      port: 46379

  rabbitmq:
    host: localhost
    port: 45672
    username: myuser
    password: secret

  datasource:
    url: jdbc:postgresql://localhost:45432/wechat
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  ai:
    openai:
      api-key: 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
      base-url: https://integrate.api.nvidia.com/v1
      chat:
        temperature: 0.1
        timeout: 60m
        options:
          model: deepseek-ai/deepseek-v4-flash
      audio:
        transcription:
          timeout: 60m
          base-url: http://localhost:48000/v1/
          options:
            model: large-v3

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

custom-ai:
  multimodal:
    base-url: https://integrate.api.nvidia.com/v1
    api-key: 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
    model: nvidia/nemotron-nano-12b-v2-vl

storage:
  upload-dir: ${HOME}/uploads
