package com.wechat.wechatsummary.service;

import com.openai.errors.InternalServerException;
import com.openai.errors.RateLimitException;
import java.net.URI;
import java.util.Base64;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.audio.transcription.AudioTranscriptionPrompt;
import org.springframework.ai.audio.transcription.AudioTranscriptionResponse;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.content.Media;
import org.springframework.ai.openai.OpenAiAudioTranscriptionModel;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.retry.annotation.Backoff;
import org.springframework.retry.annotation.Retryable;
import org.springframework.stereotype.Service;
import org.springframework.util.MimeType;

/**
 * Service responsible for interacting with various AI capabilities including audio transcription,
 * text summaries, rolling chat analysis, and image description.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class AiService {

    private final ChatClient chatClient;
    private final @Qualifier("multimodalChatClient") ChatClient multimodalChatClient;
    private final OpenAiAudioTranscriptionModel transcriptionModel;

    /**
     * Calls the Whisper transcription model with automatic retry support.
     *
     * <p>Retries are performed when the request fails due to rate limiting.</p>
     *
     * @param prompt transcription request containing the audio source
     * @return transcription response containing the text metadata
     */
    @Retryable(
        retryFor = {RateLimitException.class},
        maxAttempts = 3,
        backoff = @Backoff(
            delay = 30000,
            maxDelay = 3600000,
            multiplier = 2.0,
            random = true
        )
    )
    public AudioTranscriptionResponse callTranscriptionWithRetry(AudioTranscriptionPrompt prompt) {
        log.info("Initiating audio transcription request via Whisper model...");
        try {
            AudioTranscriptionResponse response = transcriptionModel.call(prompt);
            log.info("Audio transcription successfully completed.");
            return response;
        } catch (RateLimitException e) {
            log.warn(
                "Rate limit hit during audio transcription. Retrying based on backoff policy... Error: {}",
                e.getMessage());
            throw e;
        } catch (Exception e) {
            log.error("Unexpected error occurred during audio transcription execution.", e);
            throw e;
        }
    }

    /**
     * Calls the Spring AI ChatClient to generate an audio summary.
     *
     * <p>This method is retried automatically when transient failures occur,
     * such as API rate limiting or HTTP 5xx server errors.</p>
     *
     * @param transcript transcription generated by Whisper
     * @return summarized text
     */
    @Retryable(
        retryFor = {
            RateLimitException.class,
            org.springframework.web.client.HttpServerErrorException.class
        },
        maxAttempts = 10,
        backoff = @Backoff(
            delay = 30000,
            maxDelay = 3600000,
            multiplier = 2.0,
            random = true
        )
    )
    public String callChatClientToSummarizeAudioWithRetry(String transcript) {
        log.info("Requesting audio transcription summary from Spring AI ChatClient...");

        String systemPrompt = """
            你是一个负责帮忙理解马来西亚华人说话的AI，我将给你一个由另一个AI转化出来的原始语音转写句子，但是这个句子的准确率不高，你需要尽量通过该句子语义来正确将一句马来西亚华语口语转写成中文普通话书面语。
            例子：
             A：
            
             Eh cibeh long time no see leh！Lu 去哪里hilang料？WhatsApp你又blue tick diam diam。
            
             普通话：
            
             哎，好久不见！你跑去哪里了？发 WhatsApp 给你，你已读也不回。
            
             B：
            
             Aiya paiseh lah，最近OT到siao。Boss一直kejar KPI，我做到beh tahan liao.
            
             普通话：
            
             不好意思，最近一直加班。老板一直催业绩，我快受不了了。
            
             A：
            
             Never mind lor。今晚jom去mamak makan，tapau一点satay，再叫teh ais kaw kaw。
            
             普通话：
            
             没关系。今晚去印度清真餐馆吃饭吧，顺便打包一点沙爹，再点一杯浓一点的冰奶茶。
            
             B：
            
             Onz lah！不过lu驾车来，我今天jam到pekcek，parking又susah gila。
            
             普通话：
            
             好啊！不过你开车来吧，我今天堵车堵得很烦，停车位也超级难找。
            
             A：
            
             Can can。等下reach了call lu。Don't fly aeroplane hor！
            
             普通话：
            
             可以。到了我打电话给你。可别放我鸽子啊！
            """;

        String userPrompt = """
            这是ASR AI尝试把语音消息写成句子的原始形式，请你尝试理解并用普通话转写以下句子，把最终句子写给我就好，不要包含任何思考、解释或标签等等额外的内容：
            %s
            """.formatted(transcript);

        try {
            // Correct Spring AI fluent chain:
            return chatClient.prompt()
                .system(systemPrompt)
                .user(userPrompt)
                .call().content(); // <-- Pass the target class type right here

        } catch (Exception e) {
            log.error("Failed to execute audio summary AI request via ChatClient", e);
            throw new RuntimeException("LLM request failed via ChatClient: " + e.getMessage(), e);
        }
    }

    /**
     * Calls the Spring AI ChatClient to perform rolling chat analysis.
     *
     * <p>The model receives the previously generated rolling summary together
     * with the next chat chunk, then produces a new consolidated summary that preserves the
     * conversation history while compressing older content.</p>
     *
     * <p>Automatic retries are performed for transient failures such as API
     * rate limiting or HTTP 5xx server errors.</p>
     *
     * @param historyContext previously generated rolling summary
     * @param currentChunk   current chat chunk to merge into the summary
     * @return updated rolling summary wrapped in {@code <summary>} tags
     */
    @Retryable(
        retryFor = {RateLimitException.class,
            InternalServerException.class},
        maxAttempts = 10,
        backoff = @Backoff(delay = 30000, maxDelay = 3600000, multiplier = 2.0, random = true)
    )
    public String callChatClientToSummarizeTextWithRetry(String historyContext,
        String currentChunk) {
        log.info("Requesting rolling chat consolidation summary from ChatClient...");
        if (log.isDebugEnabled()) {
            log.debug("History context size: {} chars, Current chunk size: {} chars",
                historyContext != null ? historyContext.length() : 0,
                currentChunk != null ? currentChunk.length() : 0);
        }

        String refineSystemPrompt = """
            # 微信聊天记录摘要任务 - 严格规范
            
            你是一个冷静、客观、专门处理大马华人网络社群（包含二次元/网黑/面子书撕逼）群聊记录的审计员。你必须使用极其接地气、通俗且直接的“吃瓜/纪实语调”，严禁对聊天内容进行任何学术化、社会学或哲学高度的升华。
            
            ### 🚨 严格禁忌词与替代方案（违者扣除所有Token分）：
            - 严禁使用以下虚空造词与神棍黑话：“模因”、“语境”、“身份认同”、“结构”、“博羞”、“模因义图”、“光复之战”、“权力纠纷”。
            - 遇到群友用低俗语言人身攻击，直接写：“X用粗口/低俗语言（如叫爸爸、骂脏话）攻击Y”，严禁写成“探讨妇女权益/重演历史情节”。
            - 遇到群友发语音胡言乱语，直接写：“群友语音胡口嗨/说废话转移视线”，严禁将其解读为“制造二次元侦探/组织教材/社会学隐喻”。
            - 遇到大段英文表情包描述（如 "In the image...", "Without an image to analyze..."），这是系统的图片识别报错，请直接忽略，严禁将其翻译并脑补成群聊里的真实事件（例如不要把 book/notebook 脑补成“组织教材”）。
            
            ### 📝 术语对照表：
            - 547：一个大马本地的网络群组/团队名。
            - OKU：指残疾人证（大马专属），在群内被群友用来当成“智障/免死金牌”互相嘴臭。
            - lanjiao / 林北 / 塞林木：大马闽南语粗口，直接归类为“爆粗口/人身攻击”。""";

        String userPrompt = """
            请以文本内容为主，有标记的媒体内容为辅来总结以下微信聊天记录。你的聊天总结需要包含前情内容。请直接输出最终文本就行，无须包含思考、注解、标签等等。你需要让读者从来开始也能读懂群聊内容
            
            聊天内容：
            {currentChunk}
            
            以下是前情提要，主要负责帮助你理解上面的聊天内容：
            {historyContext}
            """;

        try {
            String summaryResult = chatClient.prompt()
//                .system(refineSystemPrompt)
                .user(user -> user.text(userPrompt)
                    .param("historyContext", historyContext)
                    .param("currentChunk", currentChunk))
                .call()
                .content();

            log.info("Rolling chat history analysis completed successfully.");
            return summaryResult;

        } catch (RateLimitException | org.springframework.web.client.HttpServerErrorException e) {
            log.warn("Transient error during rolling chat analysis: {}. Retrying calculation...",
                e.getMessage());
            throw e;
        } catch (Exception e) {
            log.error("Failed to execute rolling chat analysis via ChatClient", e);
            throw new RuntimeException("LLM request failed via ChatClient: " + e.getMessage(), e);
        }
    }

    /**
     * Processes an image to generate a short descriptive summary or extract text elements.
     *
     * <p>Retries across any fallback exception for up to 4 sequential attempts.</p>
     *
     * @param imageBytes the raw binary data of the target image
     * @param mimeType   media definition type (e.g. image/jpeg, image/png)
     * @param filePath   the file identifier string utilized for tracing logs
     * @return summary text describing the processed image composition
     */
    @Retryable(
        retryFor = Exception.class,
        maxAttempts = 4,
        backoff = @Backoff(
            delay = 2000,
            multiplier = 2.0,
            maxDelay = 10000
        )
    )
    public String generateSummary(byte[] imageBytes, String mimeType, String filePath) {
        log.info("Processing image description analysis for file context: {}", filePath);
        if (log.isDebugEnabled()) {
            log.debug("Image payload details - MimeType: {}, Payload size: {} bytes", mimeType,
                (imageBytes != null ? imageBytes.length : 0));
        }

        // Convert the image bytes into a Base64 data URI string for guaranteed compatibility
        String base64Encoded = Base64.getEncoder().encodeToString(imageBytes);
        String dataUri = "data:" + mimeType + ";base64," + base64Encoded;

        // Build the UserMessage utilizing the official Spring AI builder pattern with Media
        UserMessage userMessage = UserMessage.builder()
            .text(
                "Describe this image in a short sentence. If there is text, extract all text accurately.")
            .media(new Media(MimeType.valueOf(mimeType), URI.create(dataUri)))
            .build();

        Prompt prompt = new Prompt(userMessage);

        ChatResponse response = multimodalChatClient.prompt(prompt)
            .call()
            .chatResponse();

        if (response == null
            || response.getResult() == null
            || response.getResult().getOutput() == null) {
            log.error(
                "AI service infrastructure returned an invalid or empty payload contract structure for file: {}",
                filePath);
            throw new RuntimeException("AI returned an empty response structure");
        }

        String outputText = response.getResult().getOutput().getText();
        log.info("Successfully extracted information and summarized target image: {}", filePath);
        return outputText;
    }

//    /**
//     * Fallback handler invoked after all retry attempts have been exhausted.
//     *
//     * @param e          failure that caused retry exhaustion
//     * @param transcript original transcription text
//     * @return fallback message containing the original transcript
//     */
//    @Recover
//    public String recoverRestClient(Throwable e, String transcript) {
//        log.error("Spring AI ChatClient failed completely after all retries. Reason: {}",
//            e.getMessage());
//
//        return "【系统提示：由于 AI 服务或网络连接当前请求过于频繁或超时，摘要生成失败。原转录文本如下：】\n"
//            + transcript;
//    }
}