package com.wechat.wechatsummary.service;

import com.openai.errors.RateLimitException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.audio.transcription.AudioTranscriptionPrompt;
import org.springframework.ai.audio.transcription.AudioTranscriptionResponse;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.content.Media;
import org.springframework.ai.openai.OpenAiAudioTranscriptionModel;
import org.springframework.retry.annotation.Backoff;
import org.springframework.retry.annotation.Retryable;
import org.springframework.stereotype.Service;
import org.springframework.util.MimeType;

/**
 * Service responsible for interacting with various AI capabilities including audio transcription,
 * text summaries, rolling chat analysis, and image description.
 */
@Service
@Slf4j
@RequiredArgsConstructor
public class AiService {

    private final ChatClient chatClient;
    private final OpenAiAudioTranscriptionModel transcriptionModel;

    /**
     * Calls the Whisper transcription model with automatic retry support.
     *
     * <p>Retries are performed when the request fails due to rate limiting.</p>
     *
     * @param prompt transcription request containing the audio source
     * @return transcription response containing the text metadata
     */
    @Retryable(
        retryFor = {RateLimitException.class},
        maxAttempts = 3,
        backoff = @Backoff(
            delay = 30000,
            maxDelay = 3600000,
            multiplier = 2.0,
            random = true
        )
    )
    public AudioTranscriptionResponse callTranscriptionWithRetry(AudioTranscriptionPrompt prompt) {
        log.info("Initiating audio transcription request via Whisper model...");
        try {
            AudioTranscriptionResponse response = transcriptionModel.call(prompt);
            log.info("Audio transcription successfully completed.");
            return response;
        } catch (RateLimitException e) {
            log.warn(
                "Rate limit hit during audio transcription. Retrying based on backoff policy... Error: {}",
                e.getMessage());
            throw e;
        } catch (Exception e) {
            log.error("Unexpected error occurred during audio transcription execution.", e);
            throw e;
        }
    }

    /**
     * Calls the Spring AI ChatClient to generate an audio summary.
     *
     * <p>This method is retried automatically when transient failures occur,
     * such as API rate limiting or HTTP 5xx server errors.</p>
     *
     * @param transcript transcription generated by Whisper
     * @return summarized text
     */
    @Retryable(
        retryFor = {
            RateLimitException.class,
            org.springframework.web.client.HttpServerErrorException.class
        },
        maxAttempts = 10,
        backoff = @Backoff(
            delay = 30000,
            maxDelay = 3600000,
            multiplier = 2.0,
            random = true
        )
    )
    public String callChatClientToSummarizeAudioWithRetry(String transcript) {
        log.info("Requesting audio transcription summary from Spring AI ChatClient...");
        if (log.isDebugEnabled()) {
            log.debug("Target transcript length for summary: {} characters",
                transcript != null ? transcript.length() : 0);
        }

        String systemPrompt = """
            你是一个精通马来西亚多元文化语言（Rojak 华语/Manglish）的智能助手。
            下面是一段马来西亚本地人的语音转录文本，其中可能混杂了华语、英语、马来语（Malay）和方言。
            
            请帮我理解这段话的核心意思，并用【规范、流畅的中文】写一段精简的摘要，列出核心要点（如有待办事项或重要结论请单独列出）。
            
            ⚠️注意：输出文本长度严格不能超过原文长度。若原文仅有一句话，请用同样简短的一句话进行提炼，严禁展开无根据的联想和脑补背景。
            """;

        String userPrompt = """
            转录文本：
            \"\"\"
            {transcript}
            \"\"\"
            """;

        try {
            String summary = chatClient.prompt()
                .system(systemPrompt)
                .user(user -> user.text(userPrompt).param("transcript", transcript))
                .call()
                .content();

            log.info("Audio transcription summary successfully generated.");
            return summary;

        } catch (RateLimitException | org.springframework.web.client.HttpServerErrorException e) {
            log.warn(
                "Transient error encountered while requesting summary: {}. Triggering automatic retry attempt.",
                e.getMessage());
            throw e;
        } catch (Exception e) {
            log.error("Failed to execute audio summary AI request via ChatClient", e);
            throw new RuntimeException("LLM request failed via ChatClient: " + e.getMessage(), e);
        }
    }

    /**
     * Calls the Spring AI ChatClient to perform rolling chat analysis.
     *
     * <p>The model receives the previously generated rolling summary together
     * with the next chat chunk, then produces a new consolidated summary that preserves the
     * conversation history while compressing older content.</p>
     *
     * <p>Automatic retries are performed for transient failures such as API
     * rate limiting or HTTP 5xx server errors.</p>
     *
     * @param historyContext previously generated rolling summary
     * @param currentChunk   current chat chunk to merge into the summary
     * @return updated rolling summary wrapped in {@code <summary>} tags
     */
    @Retryable(
        retryFor = {RateLimitException.class,
            org.springframework.web.client.HttpServerErrorException.class},
        maxAttempts = 10,
        backoff = @Backoff(delay = 30000, maxDelay = 3600000, multiplier = 2.0, random = true)
    )
    public String callChatClientToSummarizeTextWithRetry(String historyContext,
        String currentChunk) {
        log.info("Requesting rolling chat consolidation summary from ChatClient...");
        if (log.isDebugEnabled()) {
            log.debug("History context size: {} chars, Current chunk size: {} chars",
                historyContext != null ? historyContext.length() : 0,
                currentChunk != null ? currentChunk.length() : 0);
        }

        String refineSystemPrompt = """
            # Role: 编年史滚动脱水官 (Rolling Executive Summary Historian)
            
            ## 核心任务
            你正在编纂一部微信群聊长篇纪实。输入包含【历史全量总结】和【新进聊天片段】。
            你的任务是：**将历史故事高强度脱水压缩，同时将新发生的事件无缝续写在末尾。**
            最终输出必须是一篇**从头讲起、脉络清晰、毫无拼接感、且篇幅极度受控**的现代大白话纪实。
            
            ## 铁律约束（如何防止字数爆炸）
            
            1. **历史全量：无损线索，高烈度脱水**：
               - 必须保留之前发生过的**所有核心事件大纲和人物冲突**，绝对不能直接漏掉某段历史。
               - **但是，必须对老故事进行全面合并和精简！** 删掉所有历史旧账里的“谁发了什么表情、谁撤回了消息、具体的斤两数字、具体的碎嘴子对白”。
               - 示例：原本1000字的“杨和小鱼干围绕假发拉扯、整容自嘲、生日祝福、健身推多少公斤”的历史，在这一轮里必须被你高强度压缩成150字左右的骨架（如：“起初，群内围绕Cos圈乱象及杨与小鱼干的假发纠纷展开长相自嘲与整容讨论，期间夹杂短暂的生日祝福与健身动作交流。随后，话题转向……”）。
            
            2. **新进片段：详细记录，平铺直叙**：
               - 对于【新进聊天片段】中的新事件，作为最新的章节，你需要相对详细地记录其发生的时间、人物、核心冲突和结果。
               - 随着滚动推进，这一轮的“新内容”在下一轮就会变成“老历史”，并被再次脱水。
            
            3. **故事线从头到尾，严禁断层**：
               - 最终文本必须是一个整体。用“起初……随后……接着……而最新进展是……”等时间/逻辑词连贯起来。
               - 严禁出现“以下是前情提要：”等生硬的结构标签，它必须是一篇通顺的纪实故事。
            
            4. **文风：现代大白话**：
               - 禁用文言文与任何无病呻吟的煽情，只留客观事实。
            
            ## 输出格式规范
            你必须将最终融合生成的脱水全量纪实文本，完整包裹在 `<summary>` 和 `</summary>` 标签内并且将输出文本字数严格限制在1500字以内。
            
            格式示例：
            <summary>
            （这里是高强度脱水后的历史骨架 + 最新详细剧情融合而成的完整故事...）
            </summary>
            """;

        String userPrompt = """
            请将以下两部分内容，完美熔炼成一篇毫无拼接感、从头讲起的全量群聊纪实：
            
            <<<< 历史全量总结（旧内容） >>>>
            {historyContext}
            
            <<<< 新进聊天片段（待融合的新内容） >>>>
            {currentChunk}
            
            请开始你的全量融合重写：
            """;

        try {
            String summaryResult = chatClient.prompt()
                .system(refineSystemPrompt)
                .user(user -> user.text(userPrompt)
                    .param("historyContext", historyContext)
                    .param("currentChunk", currentChunk))
                .call()
                .content();

            log.info("Rolling chat history analysis completed successfully.");
            return summaryResult;

        } catch (RateLimitException | org.springframework.web.client.HttpServerErrorException e) {
            log.warn("Transient error during rolling chat analysis: {}. Retrying calculation...",
                e.getMessage());
            throw e;
        } catch (Exception e) {
            log.error("Failed to execute rolling chat analysis via ChatClient", e);
            throw new RuntimeException("LLM request failed via ChatClient: " + e.getMessage(), e);
        }
    }

    /**
     * Processes an image to generate a short descriptive summary or extract text elements.
     *
     * <p>Retries across any fallback exception for up to 4 sequential attempts.</p>
     *
     * @param imageBytes the raw binary data of the target image
     * @param mimeType   media definition type (e.g. image/jpeg, image/png)
     * @param filePath   the file identifier string utilized for tracing logs
     * @return summary text describing the processed image composition
     */
    @Retryable(
        retryFor = Exception.class,
        maxAttempts = 4,
        backoff = @Backoff(
            delay = 2000,
            multiplier = 2.0,
            maxDelay = 10000
        )
    )
    public String generateSummary(byte[] imageBytes, String mimeType, String filePath) {
        log.info("Processing image description analysis for file context: {}", filePath);
        if (log.isDebugEnabled()) {
            log.debug("Image payload details - MimeType: {}, Payload size: {} bytes", mimeType,
                (imageBytes != null ? imageBytes.length : 0));
        }

        UserMessage userMessage = new UserMessage(
            "Describe this image in a short sentence. If there is text, extract all text accurately."
        );

        userMessage.getMedia().add(
            Media.builder()
                .mimeType(MimeType.valueOf(mimeType))
                .data(imageBytes)
                .build()
        );

        Prompt prompt = new Prompt(userMessage);

        ChatResponse response = chatClient.prompt(prompt)
            .call()
            .chatResponse();

        if (response == null
            || response.getResult() == null
            || response.getResult().getOutput() == null) {
            log.error(
                "AI service infrastructure returned an invalid or empty payload contract structure for file: {}",
                filePath);
            throw new RuntimeException("AI returned an empty response structure");
        }

        String outputText = response.getResult().getOutput().getText();
        log.info("Successfully extracted information and summarized target image: {}", filePath);
        return outputText;
    }

//    /**
//     * Fallback handler invoked after all retry attempts have been exhausted.
//     *
//     * @param e          failure that caused retry exhaustion
//     * @param transcript original transcription text
//     * @return fallback message containing the original transcript
//     */
//    @Recover
//    public String recoverRestClient(Throwable e, String transcript) {
//        log.error("Spring AI ChatClient failed completely after all retries. Reason: {}",
//            e.getMessage());
//
//        return "【系统提示：由于 AI 服务或网络连接当前请求过于频繁或超时，摘要生成失败。原转录文本如下：】\n"
//            + transcript;
//    }
}